#ifndef CORE_MIGRATIONS_DATABASE_TYPING_TYPES
#define CORE_MIGRATIONS_DATABASE_TYPING_TYPES
#include "core_pg_bindings/macros/declaration.hpp"
#include "core_pg_bindings/typing/definitions.hpp"
#include "core_pg_bindings/typing/types.hpp"
#include "core_migrations/database/typing/definitions.hpp"


// DEBUG clear && g++ -P -E -I/usr/include/boost -I../../../../../core_types/cpp -I./ -I../../../../../../core_pg_bindings/venv/lib/python3.12/site-packages/pybind11/include wrapper.cpp


namespace core_migrations
{
    
};


namespace core_migrations::database
{
// NOTE TYPES
PG_CPP_ENUM_DECLARATION(CORE_MIGRATIONS_DB_EXECUTION_ACTION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_DB_PACKAGE);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_DB_EXECUTION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_DB_EXECUTION_COMMIT_HASH);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_DB_MIGRATION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_DB_EXECUTION_MIGRATION);
// NOTE FUNCTIONS
PG_CPP_INVOKABLE_DECLARATION(CORE_MIGRATIONS_DB_CREATE_EXECUTION);
PG_CPP_INVOKABLE_DECLARATION(CORE_MIGRATIONS_DB_REGISTER_EXECUTION_COMMIT_HASH);
PG_CPP_INVOKABLE_DECLARATION(CORE_MIGRATIONS_DB_REGISTER_EXECUTION_MIGRATION);
PG_CPP_INVOKABLE_DECLARATION(CORE_MIGRATIONS_DB_CREATE_MIGRATION);
PG_CPP_INVOKABLE_DECLARATION(CORE_MIGRATIONS_DB_CREATE_PACKAGE);
};


#endif
