#include <pybind11/pybind11.h>
#include "core_pg_migrations/database/namespace.hpp"


namespace py = pybind11;
namespace cm = core_pg_migrations::database;


PG_ENUM_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_EXECUTION_ACTION);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_PACKAGE);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_SNAPSHOT);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_EXECUTION);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_MIGRATION);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_MIGRATION_DEPENDENCY_RELATION);
PG_TABLE_REGISTER_SUBCLASS_REG(CORE_PG_MIGRATIONS_DB_EXECUTION_SNAPSHOT_RELATION);


PYBIND11_MODULE (database_wrapper, m) 
{
    // NOTE TYPES
    PG_ENUM_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION_ACTION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_PACKAGE, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_SNAPSHOT, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_MIGRATION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_MIGRATION_DEPENDENCY_RELATION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION_SNAPSHOT_RELATION, m);
    // NOTE FUNCTIONS
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_EXECUTION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_MIGRATION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_PACKAGE, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_SNAPSHOT, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_GET_APPLIED_SNAPSHOTS, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_REGISTER_MIGRATION_DEPENDENCIES, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_SET_PACKAGE_INTEGRITY_HASH, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_REGISTER_EXECUTION_SNAPSHOT_RELATION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_GET_INTEGRITY_HASH, m);
}

