#include <pybind11/pybind11.h>
#include "core_pg_migrations/database/declarations.hpp"


namespace py = pybind11;
namespace cm = core_pg_migrations::database;


PYBIND11_MODULE (database_wrapper, m) 
{
    // NOTE TYPES
    PG_ENUM_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION_ACTION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_PACKAGE, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_MIGRATION, m);
    PG_TABLE_REGISTER(CORE_PG_MIGRATIONS_DB_EXECUTION_MIGRATION, m);
    // NOTE FUNCTIONS
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_EXECUTION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_REGISTER_EXECUTION_MIGRATION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_MIGRATION, m);
    PG_INVOKABLE_REGISTER(CORE_PG_MIGRATIONS_DB_CREATE_PACKAGE, m);
}

