#ifndef CORE_MIGRATIONS_DATABASE_INTERFACE_TYPES
#define CORE_MIGRATIONS_DATABASE_INTERFACE_TYPES
#include "core_migrations/database/typing/definitions.hpp"
#include "core_migrations/database/typing/namespace.hpp"


namespace core_migrations
{
    
}


namespace pqxx
{
PG_DECLARE_ENUM_CONVERSION(CORE_MIGRATIONS_DB_EXECUTION_ACTION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_DB_PACKAGE);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_DB_EXECUTION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_DB_EXECUTION_COMMIT_HASH);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_DB_MIGRATION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_DB_EXECUTION_MIGRATION);
}


#endif
