[build-system]
requires = [
    "setuptools",
    "wheel",
    "core_cpp_packaging_tools==0.0.0",
    "core_types==0.0.0",
    "core_pg_bindings==0.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "core_pg_migrations"
version = "0.0.0"
description = "Core C++ migrations"
readme = "README.md"
license = { text = "GPL-3.0" }
keywords = ["test", "cmake", "extension"]
requires-python = ">=3.12"
classifiers = [
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
zip-safe = false

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
optional-dependencies = { dev = { file = "dev-requirements.txt" } }
