[build-system]
requires = ["setuptools", "wheel"]  # Add other build dependencies if needed
build-backend = "setuptools.build_meta"

[project]
name = "core_pg_migrations"
version = "1.0.0a0"
description = "Core C++ migrations"
readme = "README.md"
license = { text = "GPL-3.0" }
keywords = ["test", "cmake", "extension"]
requires-python = ">=3.12"
classifiers = [
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
zip-safe = false
