#include <pybind11/pybind11.h>

#include "mgr_manager/types.hpp"
#include "pg_definition/macros/register.hpp"


namespace py = pybind11;


PG_PY_ENUM_DECLARE_SUBCLASS_REG(PG_PACKAGE_EXECUTION_ACTION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(PG_PACKAGE_PACKAGE);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(PG_PACKAGE_EXECUTION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(PG_PACKAGE_MIGRATION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(PG_PACKAGE_MIGRATION_EXECUTION);
