#include <pybind11/pybind11.h>

#include "core_migrations/types.hpp"
#include "core_pg_bindings/macros/register.hpp"


namespace py = pybind11;


PG_PY_ENUM_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_EXECUTION_ACTION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_PACKAGE);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_EXECUTION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_MIGRATION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_EXECUTION_MIGRATION);
PG_PY_TABLE_DECLARE_SUBCLASS_REG(CORE_MIGRATIONS_EXECUTION_COMMIT_HASH);
