#ifndef CORE_PG_MIGRATIONS_BACKEND__DEFINITIONS
#define CORE_PG_MIGRATIONS_BACKEND__DEFINITIONS
#include "core_types/all.hpp"
#include "core_pg_bindings/all.hpp"


#define CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM DATACLASS_DEFINITION(\
    CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM,\
    (core_pg_migrations::backend, migration_param),\
    (DATACLASS_MEMBER(PG_TEXT, name))\
    (DATACLASS_MEMBER(PG_TEXT, snapshot))\
    (DATACLASS_MEMBER(STD_OPTIONAL(PG_TEXT), datafix_name)),\
    NONE,\
    (core_pg_migrations::backend::interface, migration_param)\
)
#define CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM_MEMBERS T_MEMBERS(CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM)
#define CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM_CONSTRUCTORS (CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM)


#define CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS DATACLASS_DEFINITION(\
    CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS,\
    (core_pg_migrations::backend, setup_parameters),\
    (DATACLASS_MEMBER(PG_TEXT, script_name))\
    (DATACLASS_MEMBER(STD_VECTOR(CORE_PG_MIGRATIONS_BACKEND_MIGRATION_PARAM), migrations))\
    (DATACLASS_MEMBER(PG_TEXT, proc_schema))\
    (DATACLASS_MEMBER(PG_TEXT, tracked_branch))\
    (DATACLASS_MEMBER(PG_TEXT, package_name))\
    (DATACLASS_MEMBER(PG_TEXT, setup_script)),\
    NONE,\
    (core_pg_migrations::backend::interface, setup_parameters)\
)
#define CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS_MEMBERS T_MEMBERS(CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS)
#define CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS_CONSTRUCTORS (CORE_PG_MIGRATIONS_BACKEND_SETUP_PARAMETERS)



#endif
