#ifndef CORE_MIGRATIONS_TYPES
#define CORE_MIGRATIONS_TYPES


#include <pqxx/pqxx>
#include "core_migrations/definitions.hpp"

// DEBUG clear && g++ -P -E -I/usr/include/boost -I../../../../../core_types/cpp -I./ -I../../../../../../core_pg_bindings/venv/lib/python3.12/site-packages/pybind11/include wrapper.cpp

namespace core_migrations
{

PG_CPP_ENUM_DECLARATION(CORE_MIGRATIONS_EXECUTION_ACTION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_PACKAGE);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_EXECUTION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_EXECUTION_COMMIT_HASH);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_MIGRATION);
PG_CPP_TABLE_DECLARATION(CORE_MIGRATIONS_EXECUTION_MIGRATION);


}

namespace pqxx
{

PG_DECLARE_ENUM_CONVERSION(CORE_MIGRATIONS_EXECUTION_ACTION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_PACKAGE);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_EXECUTION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_EXECUTION_COMMIT_HASH);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_MIGRATION);
PG_DECLARE_TABLE_CONVERSION(CORE_MIGRATIONS_EXECUTION_MIGRATION);

}


#endif
