INSERT INTO author(name)
VALUES ('author 1'),
    ('author 2'),
    ('author 3'),
    ('author 4');


INSERT INTO post(author_id, content, title, status)
VALUES (1, 'test content 1', 'test title 1', 'published'),
       (1, 'test content 2', 'test title 2', 'draft'),
       (1, 'test content 3', 'test title 3', 'waiting_approval'),
       (1, 'test content 4', 'test title 4', 'published'),
       (1, 'test content 5', 'test title 5', 'waiting_approval'),
       (2, 'test content 6', 'test title 6', 'published'),
       (2, 'test content 7', 'test title 7', 'draft'),
       (2, 'test content 8', 'test title 8', 'published'),
       (3, 'test content 9', 'test title 9', 'waiting_approval'),
       (3, 'test content 10', 'test title 10', 'published'),
       (3, 'test content 11', 'test title 11', 'published'),
       (3, 'test content 12', 'test title 12', 'waiting_approval'),
       (4, 'test content 13', 'test title 13', 'draft'),
       (4, 'test content 14', 'test title 14', 'published'),
       (4, 'test content 15', 'test title 15', 'waiting_approval'),
       (4, 'test content 15', 'test title 15', 'draft'),
       (4, 'test content 16', 'test title 16', 'published');

INSERT INTO comment(post_id, author_id, content)
VALUES (1, 1, 'test content 1'),
       (2, 1, 'test content 2'),
       (3, 1, 'test content 3'),
       (4, 1, 'test content 4'),
       (5, 1, 'test content 5'),
       (6, 2, 'test content 6'),
       (7, 2, 'test content 7'),
       (8, 2, 'test content 8'),
       (9, 3, 'test content 9'),
       (10, 3, 'test content 10'),
       (11, 3, 'test content 11'),
       (12, 3, 'test content 12'),
       (13, 4, 'test content 13'),
       (14, 4, 'test content 14'),
       (15, 4, 'test content 15'),
       (16, 4, 'test content 15'),
       (1, 4, 'test content 16'),
       (1, 1, 'test content 1'),
       (1, 1, 'test content 2'),
       (2, 1, 'test content 3'),
       (3, 1, 'test content 4'),
       (4, 1, 'test content 5'),
       (5, 2, 'test content 6'),
       (6, 2, 'test content 7'),
       (7, 2, 'test content 8'),
       (8, 3, 'test content 9'),
       (9, 3, 'test content 10'),
       (10, 3, 'test content 11'),
       (11, 3, 'test content 12'),
       (12, 4, 'test content 13'),
       (13, 4, 'test content 14'),
       (14, 4, 'test content 15'),
       (15, 4, 'test content 15'),
       (16, 4, 'test content 16');
