#ifndef PG_PACKAGE_DEFINITIONS
#define PG_PACKAGE_DEFINITIONS


#include "pg_definition/macros/definition.hpp"
#include "pg_definition/types.hpp"


#define PG_PACKAGE_EXECUTION_ACTION PG_ENUM_DEFINITION(\
    PG_PACKAGE_EXECUTION_ACTION,\
    (mgr_manager, execution_action),\
    (PG_ENUM_VALUE(setup))\
    (PG_ENUM_VALUE(upgrade))\
    (PG_ENUM_VALUE(downgrade))\
)
#define PG_PACKAGE_EXECUTION_ACTION_CONSTRUCTORS (PG_PACKAGE_EXECUTION_ACTION)


#define PG_PACKAGE_PACKAGE PG_TABLE_NO_BASES_DEFINITION(\
    PG_PACKAGE_PACKAGE,\
    (mgr_manager, package),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_TEXT, name))\
    (PG_COLUMN(PG_TEXT, version))\
    (PG_COLUMN(PG_TEXT, branch_name))\
    (PG_COLUMN(PG_TEXT, last_commit_hash))\
    (PG_COLUMN(PG_TIMESTAMPTZ, last_updated_at))\
)
#define PG_PACKAGE_PACKAGE_CONSTRUCTORS (PG_PACKAGE_PACKAGE)
#define PG_PACKAGE_PACKAGE_MEMBERS T_DIRECT_MEMBERS(PG_PACKAGE_PACKAGE)


#define PG_PACKAGE_EXECUTION PG_TABLE_NO_BASES_DEFINITION(\
    PG_PACKAGE_EXECUTION,\
    (mgr_manager, execution),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_INT8, package_id))\
    (PG_COLUMN(PG_TIMESTAMPTZ, created_at))\
    (PG_COLUMN(PG_TEXT, commit_hash))\
    (PG_COLUMN(PG_PACKAGE_EXECUTION_ACTION, action))\
)
#define PG_PACKAGE_EXECUTION_CONSTRUCTORS (PG_PACKAGE_EXECUTION)
#define PG_PACKAGE_EXECUTION_MEMBERS T_DIRECT_MEMBERS(PG_PACKAGE_EXECUTION)


#define PG_PACKAGE_MIGRATION PG_TABLE_NO_BASES_DEFINITION(\
    PG_PACKAGE_MIGRATION,\
    (mgr_manager, migration),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_INT8, package_id))\
    (PG_COLUMN(PG_TEXT, name))\
    (PG_COLUMN(PG_TEXT, datafix_name))\
    (PG_COLUMN(PG_TIMESTAMPTZ, created_at))\
)
#define PG_PACKAGE_MIGRATION_CONSTRUCTORS (PG_PACKAGE_MIGRATION)
#define PG_PACKAGE_MIGRATION_MEMBERS T_DIRECT_MEMBERS(PG_PACKAGE_MIGRATION)


#define PG_PACKAGE_MIGRATION_EXECUTION PG_TABLE_NO_BASES_DEFINITION(\
    PG_PACKAGE_MIGRATION_EXECUTION,\
    (mgr_manager, migration_execution),\
    (PG_COLUMN(PG_INT8, migration_id))\
    (PG_COLUMN(PG_INT8, execution_id))\
)
#define PG_PACKAGE_MIGRATION_EXECUTION_CONSTRUCTORS (PG_PACKAGE_MIGRATION_EXECUTION)
#define PG_PACKAGE_MIGRATION_EXECUTION_MEMBERS T_DIRECT_MEMBERS(PG_PACKAGE_MIGRATION_EXECUTION)


#endif
