#ifndef PG_PACKAGE_TYPES
#define PG_PACKAGE_TYPES


#include <pqxx/pqxx>
#include "mgr_manager/definitions.hpp"

// DEBUG clear && g++ -P -E -I/usr/include/boost -I../../../../../base_types/cpp -I./ -I../../../../../../pg_definition/venv/lib/python3.12/site-packages/pybind11/include wrapper.cpp

namespace mgr_manager
{

PG_CPP_ENUM_DECLARATION(PG_PACKAGE_EXECUTION_ACTION);
PG_CPP_TABLE_DECLARATION(PG_PACKAGE_PACKAGE);
PG_CPP_TABLE_DECLARATION(PG_PACKAGE_EXECUTION);
PG_CPP_TABLE_DECLARATION(PG_PACKAGE_MIGRATION);
PG_CPP_TABLE_DECLARATION(PG_PACKAGE_MIGRATION_EXECUTION);

}

namespace pqxx
{

PG_DECLARE_ENUM_CONVERSION(PG_PACKAGE_EXECUTION_ACTION);
PG_DECLARE_TABLE_CONVERSION(PG_PACKAGE_PACKAGE);
PG_DECLARE_TABLE_CONVERSION(PG_PACKAGE_EXECUTION);
PG_DECLARE_TABLE_CONVERSION(PG_PACKAGE_MIGRATION);
PG_DECLARE_TABLE_CONVERSION(PG_PACKAGE_MIGRATION_EXECUTION);

}


#endif
