BEGIN
RAISE NOTICE "EXECUTING MIGRATION {migration_name}";
{migration_script}
EXCEPTION WHEN OTHERS THEN
RAISE NOTICE "MIGRATION {migration_name} ERROR";
RAISE NOTICE "STATE: %s, ERROR: %s.", SQLSTATE, SQLERRM;
RAISE NOTICE "ROLLING BACK..."
ROLLBACK;
END;
