[migration]
migration_submodule = ".migration"
database_dsn = "host=172.18.0.1 dbname=mutzhub port=5432 user=mutzhub password=WtbNMMpX46iynzjVobrh8Qu7omvFIL9JEvbkLYYCpCJNIwDWnBwcVquhk6vXe6En"
var_directory = "./var"
datafix_directory = "./datafix"
tracked_branch = "trunk"
search_path = ["core_pg_migrations"]
procedure_schema = "core_migration_procedure"
schema = "core_pg_migrations"
