[migration]
migration_submodule = ".migration"
var_directory = "./var"
datafix_directory = "./datafix"
tracked_branch = "trunk"
remote_name = "sgs"
procedure_schema = ".database.core_pg_migration_execution_procedures"
schema = ".database.core_pg_migrations"
